//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockViewer.Position.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockViewer.Position.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Symbol.
        /// </summary>
        public static string ActionSearchSymbol {
            get {
                return ResourceManager.GetString("ActionSearchSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Symbol(s).
        /// </summary>
        public static string AddSymbols {
            get {
                return ResourceManager.GetString("AddSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Basis.
        /// </summary>
        public static string CostBasis {
            get {
                return ResourceManager.GetString("CostBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAST.
        /// </summary>
        public static string Fast {
            get {
                return ResourceManager.GetString("Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain/Loss %.
        /// </summary>
        public static string GainLossPercentage {
            get {
                return ResourceManager.GetString("GainLossPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Value.
        /// </summary>
        public static string MarketValue {
            get {
                return ResourceManager.GetString("MarketValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Off.
        /// </summary>
        public static string RefreshOff {
            get {
                return ResourceManager.GetString("RefreshOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Rate.
        /// </summary>
        public static string RefreshRate {
            get {
                return ResourceManager.GetString("RefreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Symbol(s).
        /// </summary>
        public static string RemoveSymbols {
            get {
                return ResourceManager.GetString("RemoveSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares.
        /// </summary>
        public static string Shares {
            get {
                return ResourceManager.GetString("Shares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon StockIndexDown {
            get {
                object obj = ResourceManager.GetObject("StockIndexDown", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon StockIndexUp {
            get {
                object obj = ResourceManager.GetObject("StockIndexUp", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfStockPosition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;StockPosition&gt;
        ///    &lt;TickerSymbol&gt;AARTIIND&lt;/TickerSymbol&gt;
        ///    &lt;CostBasis&gt;676.75&lt;/CostBasis&gt;
        ///    &lt;Shares&gt;10&lt;/Shares&gt;
        ///    &lt;WL52&gt;15.00&lt;/WL52&gt;
        ///    &lt;WH52&gt;68.700&lt;/WH52&gt;
        ///  &lt;/StockPosition&gt;
        ///  &lt;StockPosition&gt;
        ///    &lt;TickerSymbol&gt;AARVEEDEN&lt;/TickerSymbol&gt;
        ///    &lt;CostBasis&gt;1900.22&lt;/CostBasis&gt;
        ///    &lt;Shares&gt;100&lt;/Shares&gt;
        ///    &lt;WL52&gt;11.50&lt;/WL52&gt;
        ///    &lt;WH52 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StockPositions {
            get {
                return ResourceManager.GetString("StockPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 52 Week High.
        /// </summary>
        public static string WH52 {
            get {
                return ResourceManager.GetString("WH52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 52 Week Low.
        /// </summary>
        public static string WL52 {
            get {
                return ResourceManager.GetString("WL52", resourceCulture);
            }
        }
    }
}
